name: Oqvest CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and test
        run: |
          npm i

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: oqvest:latest

      - name: SSH into the VPS server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy the app
        run: |
          docker stop oqvest || true
          docker rm oqvest || true
          docker pull oqvest:latest
          docker run -d -p 80:80 --name oqvest oqvest:latest
